/**
 * Vendor offers for miners
 * Links miners to sellers with pricing and stock info
 */

const vendorOffers = [
  // Whatsminer M79S offers
  {
    miner_id: 3,
    miner_slug: 'whatsminer-m79s-1-35ph-s',
    vendor: 'Crypto Miner Bros',
    country: 'United States',
    location: '25m',
    condition: 'Brand New',
    stock: 'In Stock',
    price: 12289.00,
    price_per_th: 9102.96,
    roi_days: 306,
    coupon: 'MOON70',
    shop_url: 'https://www.cryptominerbros.com',
  },
  {
    miner_id: 3,
    miner_slug: 'whatsminer-m79s-1-35ph-s',
    vendor: 'ASIC Marketplace',
    country: 'United States',
    location: '25m',
    condition: 'Brand New',
    stock: 'In Stock',
    price: 12289.00,
    price_per_th: 9102.96,
    roi_days: 306,
    coupon: 'MOON70',
    shop_url: 'https://www.asicmarketplace.com',
  },
  {
    miner_id: 3,
    miner_slug: 'whatsminer-m79s-1-35ph-s',
    vendor: 'One Miners',
    country: 'United States',
    location: '40m',
    condition: 'Brand New',
    stock: 'In Stock',
    price: 12478.00,
    price_per_th: 9242.96,
    roi_days: 311,
    coupon: null,
    shop_url: 'https://www.oneminers.com',
  },
  {
    miner_id: 3,
    miner_slug: 'whatsminer-m79s-1-35ph-s',
    vendor: 'Yes Mining',
    country: 'Hong Kong',
    location: '45m',
    condition: 'Brand New',
    stock: 'In Stock',
    price: 18680.00,
    price_per_th: 13837.04,
    roi_days: 466,
    coupon: null,
    shop_url: 'https://www.yesmining.com',
  },
  {
    miner_id: 3,
    miner_slug: 'whatsminer-m79s-1-35ph-s',
    vendor: 'millionminer.com',
    country: 'Germany',
    location: '35m',
    condition: 'Brand New',
    stock: 'Out of Stock',
    price: 19299.00,
    price_per_th: 14295.56,
    roi_days: 481,
    coupon: null,
    shop_url: 'https://www.millionminer.com',
  },

  // Antminer S21 Pro offers
  {
    miner_id: 1,
    miner_slug: 'antminer-s21-pro-234t',
    vendor: 'Crypto Miner Bros',
    country: 'United States',
    location: '25m',
    condition: 'Brand New',
    stock: 'In Stock',
    price: 8500.00,
    price_per_th: 6837.61,
    roi_days: 280,
    coupon: null,
    shop_url: 'https://www.cryptominerbros.com',
  },
  {
    miner_id: 1,
    miner_slug: 'antminer-s21-pro-234t',
    vendor: 'One Miners',
    country: 'United States',
    location: '40m',
    condition: 'Brand New',
    stock: 'In Stock',
    price: 8700.00,
    price_per_th: 7008.55,
    roi_days: 290,
    coupon: null,
    shop_url: 'https://www.oneminers.com',
  },
  {
    miner_id: 1,
    miner_slug: 'antminer-s21-pro-234t',
    vendor: 'Yes Mining',
    country: 'Hong Kong',
    location: '45m',
    condition: 'Brand New',
    stock: 'In Stock',
    price: 11200.00,
    price_per_th: 9017.09,
    roi_days: 380,
    coupon: null,
    shop_url: 'https://www.yesmining.com',
  },

  // Antminer L7 offers
  {
    miner_id: 4,
    miner_slug: 'antminer-l7-9500m',
    vendor: 'Crypto Miner Bros',
    country: 'United States',
    location: '25m',
    condition: 'Brand New',
    stock: 'In Stock',
    price: 6800.00,
    price_per_th: null,
    roi_days: 320,
    coupon: null,
    shop_url: 'https://www.cryptominerbros.com',
  },
  {
    miner_id: 4,
    miner_slug: 'antminer-l7-9500m',
    vendor: 'One Miners',
    country: 'United States',
    location: '40m',
    condition: 'Brand New',
    stock: 'In Stock',
    price: 7200.00,
    price_per_th: null,
    roi_days: 340,
    coupon: null,
    shop_url: 'https://www.oneminers.com',
  },
];

module.exports = { vendorOffers };
